#!/bin/bash

COMPILER_NAME=gcc
LINKER_NAME=g++

# url: https://en.wikipedia.org/wiki/Software_versioning
COMPILER_MAJOR_VERSION=5
COMPILER_MINOR_VERSION=3
COMPILER=$COMPILER_NAME-$COMPILER_MAJOR_VERSION.$COMPILER_MINOR_VERSION
